---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# copdr

<!-- badges: start -->
<!-- badges: end -->

The goal of copdr is to produce a model that identifies peaks within a dataset that correspond to earthquake displacement magnitudes. This code has several functions to streamline the import and summation of probability distribution functions (PDFs), i.e. Gaussian curves, produced from 'LaDiCaoz'. LaDiCaoz is a Matlab program that allows you to 'backslip' offset on a fault identified from aerial imagery such as digital elevation models (DEMs) or digital surface models (DSMs). The goals of 'copdr' are to visualize the combined PDF dataset as a cumulative offset probability distribution (COPD) function, and filter out the PDFs that have high uncertainties (i.e. large standard deviations, high coefficient of variation, etc). 


## Installation

You can install the development version of copdr from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("AubreyLaPlante/copdr")
```
