#' Filter offset data by COV values
#'
#'
#' Combine all offset data from the mat files.
#'
#' @importFrom dplyr select bind_cols
#' @importFrom tidyselect contains
#' @importFrom stats na.omit
#' @param backslip_ref A reference datatable containing coefficient of variation (COV) values.
#' @param offset_ID The column number in the reference datatable 'backslip_ref' corresponding
#' to the names of offset .mat files
#' @param offset_type Input can be "lateral", "vertical" or "total". Any other input
#' will result in an error.
#' @param COV_values The vector containing the cutoff COV values you would like
#' to create filtered datasets for.
#' @param COV_mat The input filtered reference file generated by the function 'filter.covREF'
#' @param backslip_data The list corresponding to combined lateral, vertical and total PDFs.
#' The default is 'backslip_data'.
#' @return A filtered list of matrices. Each matrix will have a set of PDFs filtered by COV values
#' as referenced in the COV_mat file.
#' @export
#'
#'
#'
#'
#'


filter.covDAT <- function(backslip_ref,offset_ID,offset_type,COV_values,COV_mat, backslip_data = backslip_data){
     #create a list to store matrices
     COV_filtDAT <- vector(mode='list', length=length(COV_values))
     names(COV_filtDAT) <- c(paste("lessthan",COV_values, sep="_"))
     ## loop to select only data that are referenced in respective COV_mat file ##
     if(offset_type == "lateral"){
          for(i in 1:length(COV_values)){
               lat <- backslip_data[[1]]
               h_x <-  lat[[1]]
               subID <- stats::na.omit(COV_mat[,c(1,i+1)])[,1]
               cov_select <- dplyr::select(lat, tidyselect::contains(subID$offset_ID))
               cov_select <- dplyr::bind_cols(h_x, cov_select)
               colnames(cov_select)[1] = "h_x"
               cov_selectSUM <- as.matrix(apply(cov_select[2:length(cov_select)], 1, sum))
               COV_filtDAT[[i]] <- dplyr::bind_cols(x = cov_select, y = cov_selectSUM)
          }
     }

     if(offset_type == "vertical"){
          for(i in 1:length(COV_values)){
               vert <- backslip_data[[2]]
               z_x <- vert[[1]]
               subID <- stats::na.omit(COV_mat[,c(1,i+1)])[,1]
               cov_select <- dplyr::select(vert, tidyselect::contains(subID$offset_ID))
               cov_select <- dplyr::bind_cols(z_x, cov_select)
               colnames(cov_select)[1] = "z_x"
               cov_selectSUM <- as.matrix(apply(cov_select[2:length(cov_select)], 1, sum))
               COV_filtDAT[[i]] <- dplyr::bind_cols(x = cov_select, y = cov_selectSUM)
          }
     }

     if(offset_type == "total"){
          for(i in 1:length(COV_values)){
               tot <- backslip_data[[3]]
               t_x <- tot[[1]]
               subID <- stats::na.omit(COV_mat[,c(1,i+1)])[,1]
               cov_select <- dplyr::select(tot, tidyselect::contains(subID$offset_ID))
               cov_select <- dplyr::bind_cols(t_x, cov_select)
               colnames(cov_select)[1] = "t_x"
               cov_selectSUM <- as.matrix(apply(cov_select[2:length(cov_select)], 1, sum))
               COV_filtDAT[[i]] <- dplyr::bind_cols(x = cov_select, y = cov_selectSUM)
          }
     }
     return(COV_filtDAT)
}


